DROP TABLE IF EXISTS dms CASCADE;
CREATE TABLE dms (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  msg TEXT,
  time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
